apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiZm9nYW5nLXlhbm4iLCJwYXNzd29yZCI6ImdocF9pUklkNGlsNE52d2hqakdtRmpRVDdIRnZxZzZQeWQ0WXV6N2QiLCJhdXRoIjoiWm05bllXNW5MWGxoYm00NloyaHdYMmxTU1dRMGFXdzBUblozYUdwcVIyMUdhbEZVTjBoR2RuRm5ObEI1WkRSWmRYbzNaQT09In19fQ==
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
